apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-custom
  template:
    metadata:
      labels:
        app: nginx-custom
    spec:
      containers:
      - name: nginx
        image: custom-nginx-lab:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
